"""
Models for login_app.
Currently using Django's built-in User model.
Custom user model can be added here if needed in the future.
"""
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class UserProfile(models.Model):
    """
    Extended user profile for tracking free generations and usage.
    Created automatically when a User is created via signal.
    """
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile'
    )
    free_generations_remaining = models.IntegerField(
        default=10,
        help_text="Number of free meal plan generations remaining (lifetime limit)"
    )
    total_generations = models.IntegerField(
        default=0,
        help_text="Total number of meal plans generated by this user"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "User Profile"
        verbose_name_plural = "User Profiles"

    def __str__(self):
        return f"Profile for {self.user.username}"

    def has_free_generations(self) -> bool:
        """Check if user has any free generations remaining."""
        return self.free_generations_remaining > 0

    def use_free_generation(self) -> bool:
        """
        Use one free generation credit.
        Returns True if successful, False if no credits remaining.
        """
        if self.free_generations_remaining > 0:
            self.free_generations_remaining -= 1
            self.total_generations += 1
            self.save(update_fields=['free_generations_remaining', 'total_generations', 'updated_at'])
            return True
        return False


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Automatically create a UserProfile when a new User is created."""
    if created:
        UserProfile.objects.create(user=instance)



