# Generated by Django 5.2.14 on 2026-06-13 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Processed Webhook Event',
                'verbose_name_plural': 'Processed Webhook Events',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], help_text='Matches Stripe metadata + the entitlement tier.', max_length=20, unique=True)),
                ('name', models.CharField(help_text="Display name, e.g. 'Eatalníček Standard'.", max_length=100)),
                ('price_czk', models.PositiveIntegerField(help_text='Monthly price in CZK (display + sanity check).')),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe recurring Price ID (price_…). Test and live differ; set per environment.', max_length=255)),
                ('monthly_plan_quota', models.PositiveIntegerField(help_text='Meal plans generatable per billing period (Standard 7, Premium 30).')),
                ('edits_per_plan', models.PositiveIntegerField(help_text='Allowed edits per generated plan (Standard 10, Premium 5).')),
                ('allow_multi_store', models.BooleanField(default=False, help_text='Multi-store price optimization (Premium only).')),
                ('is_active', models.BooleanField(default=True, help_text='Show on the pricing page.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(db_index=True, help_text='Stripe Subscription ID (sub_…). Webhook idempotency anchor.', max_length=255, unique=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='From Stripe; the entitlement expiry.', null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Set when the user cancels via the Customer Portal.')),
                ('plans_used_this_period', models.PositiveIntegerField(default=0, help_text='Reset to 0 on each renewal (invoice.paid).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
