# Generated by Django 5.2.14 on 2026-09-22 17:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rename_plans_varto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ukládá se velkými písmeny.', max_length=40, unique=True)),
                ('percent_off', models.PositiveSmallIntegerField(help_text='1–100. 100 = zdarma bez karty.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('duration_kind', models.CharField(choices=[('lifetime', 'Navždy'), ('months', 'N měsíců'), ('first_invoice', 'Jen první platba / 1 měsíc')], default='lifetime', max_length=20)),
                ('duration_months', models.PositiveSmallIntegerField(blank=True, help_text="Jen pro 'N měsíců'.", null=True)),
                ('tiers', models.JSONField(blank=True, default=list, help_text='Seznam povolených tarifů, např. ["premium"]. Prázdné = libovolný.')),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Prázdné = neomezeně.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Prázdné = nikdy.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, help_text='Interní poznámka (komu, kampaň).')),
                ('stripe_coupon_id', models.CharField(blank=True, help_text='Vyplní se automaticky pro kódy pod 100 %.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo kód',
                'verbose_name_plural': 'Promo kódy',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='grant_expires_at',
            field=models.DateTimeField(blank=True, help_text='Promo rows only. NULL = lifetime.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='source',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('promo', 'Promo kód')], db_index=True, default='stripe', help_text='promo rows have no Stripe ids and expire via grant_expires_at.', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, help_text='Stripe rows: entitlement expiry from Stripe. Promo rows: rolling 30-day quota window.', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Subscription ID (sub_…). Webhook idempotency anchor. NULL for promo grants.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.promocode'),
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='billing.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uplatnění promo kódu',
                'verbose_name_plural': 'Uplatnění promo kódů',
                'unique_together': {('promo_code', 'user')},
            },
        ),
    ]
