# Generated by Django 5.2.14 on 2026-09-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_promo_codes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(('percent_off__gte', 1), ('percent_off__lte', 100)), name='promocode_percent_off_1_100'),
        ),
    ]
