# Generated by Django 5.2.14 on 2026-07-14 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(blank=True, default='', max_length=255)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=255)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=255)),
                ('utm_content', models.CharField(blank=True, default='', max_length=255)),
                ('utm_term', models.CharField(blank=True, default='', max_length=255)),
                ('fbclid', models.CharField(blank=True, default='', max_length=512)),
                ('fbp', models.CharField(blank=True, default='', max_length=255)),
                ('fbc', models.CharField(blank=True, default='', max_length=512)),
                ('landing_at', models.DateTimeField(blank=True, null=True)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_version', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_attribution', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
