import os
import logging
from django.http import HttpResponse
from django.shortcuts import render
from django.conf import settings

logger = logging.getLogger(__name__)

def health_check(request):
    """
    Dedicated health check endpoint for DigitalOcean.
    Always returns 200 to prevent container restarts during build debugging.
    """
    return HttpResponse("OK", status=200)

def react_app_view(request):
    """
    Serves the React frontend. In production, this looks for the index.html 
    inside the 'dist' folder generated by Vite.
    """
    index_path = os.path.join(settings.REACT_BUILD_DIR, 'index.html')
    
    if not os.path.exists(index_path):
        logger.error(f"Frontend build not found at {index_path}")
        # Return 200 during debug so health checks pass, but show the error UI
        return HttpResponse(
            f"""
            <html>
                <body style="background: #0a0f1e; color: white; text-align: center; font-family: sans-serif; padding-top: 100px;">
                    <div style="max-width: 600px; margin: 0 auto; padding: 40px; background: #161d2f; border-radius: 24px; border: 1px solid #2563eb; box-shadow: 0 20px 50px rgba(0,0,0,0.5);">
                        <h1 style="color: #2563eb; font-size: 2.5em;">Vite Build Missing</h1>
                        <p style="font-size: 1.1em; color: #d1d5db;">The production <code>dist</code> folder is missing in the container.</p>
                        <div style="text-align: left; background: #0a0f1e; padding: 20px; border-radius: 12px; margin: 20px 0; font-family: monospace; font-size: 0.9em; border: 1px solid #1f2937;">
                            <span style="color: #6b7280;"># Expected Path:</span><br>
                            {index_path}<br><br>
                            <span style="color: #6b7280;"># Current Directory:</span><br>
                            {os.getcwd()}
                        </div>
                        <p style="font-size: 0.8em; color: #9ca3af;">Verify <code>npm run build</code> succeeded in your Dockerfile.</p>
                    </div>
                </body>
            </html>
            """,
            status=200 
        )

    try:
        with open(index_path, 'r') as f:
            return HttpResponse(f.read())
    except Exception as e:
        logger.error(f"Error reading index.html: {str(e)}")
        return HttpResponse("Internal Server Error: Failed to load frontend.", status=500)

def debug_prompt_view(request):
    """
    Renders the debug prompt template.
    Template location: llm_diet_planner_project/templates/debug_prompt.html
    """
    return render(request, 'debug_prompt.html')

def test_ui_view(request):
    """
    Renders the test UI template.
    Template location: llm_diet_planner_project/templates/test_ui.html
    """
    return render(request, 'test_ui.html')