import os
import logging
from django.http import HttpResponse
from django.shortcuts import render
from django.conf import settings

logger = logging.getLogger(__name__)

def react_app_view(request):
    """
    Serves the React frontend. In production, this looks for the index.html 
    inside the 'dist' folder generated by Vite.
    """
    # Use the absolute path defined in settings to avoid path resolution errors
    index_path = os.path.join(settings.REACT_BUILD_DIR, 'index.html')
    
    if not os.path.exists(index_path):
        logger.error(f"Frontend build not found at {index_path}")
        return HttpResponse(
            f"""
            <html>
                <body style="background: #0a0f1e; color: white; text-align: center; font-family: sans-serif; padding-top: 100px;">
                    <div style="max-width: 600px; margin: 0 auto; padding: 20px; background: #161d2f; border-radius: 20px; border: 1px solid #2563eb;">
                        <h1 style="color: #2563eb;">Vite Build Missing</h1>
                        <p>The production 'dist' folder is missing or incorrectly mapped.</p>
                        <p style="font-size: 0.9em; color: #9ca3af;">Expected index.html at: <br><code>{index_path}</code></p>
                        <hr style="border: 0; border-top: 1px solid #1f2937; margin: 20px 0;">
                        <p style="font-size: 0.8em;">Check deployment logs for errors during <code>npm run build</code> or <code>collectstatic</code>.</p>
                    </div>
                </body>
            </html>
            """,
            status=503
        )

    try:
        with open(index_path, 'r') as f:
            return HttpResponse(f.read())
    except Exception as e:
        logger.error(f"Error reading index.html: {str(e)}")
        return HttpResponse("Internal Server Error: Failed to load frontend.", status=500)

def debug_prompt_view(request):
    """
    Renders the debug prompt template.
    Template location: llm_diet_planner_project/templates/debug_prompt.html
    """
    return render(request, 'debug_prompt.html')

def test_ui_view(request):
    """
    Renders the test UI template.
    Template location: llm_diet_planner_project/templates/test_ui.html
    """
    return render(request, 'test_ui.html')