import os
import logging
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.conf import settings
from pathlib import Path

logger = logging.getLogger(__name__)

def health_check(request):
    """
    Standard health check for DigitalOcean.
    Must return 200 OK for the app to be considered 'Healthy'.
    """
    return HttpResponse("OK", status=200)

def react_app_view(request):
    """
    The Single Entry Point for the React Application (SPA).
    
    This view serves the 'index.html' file generated by Vite. 
    It is the only view in the entire project that should return HTML 
    for frontend routes.
    """
    path_str = request.path.lstrip('/')
    
    # --- CRITICAL: MIME TYPE PROTECTION ---
    # If the request is for a file (contains a dot) and it reached this view,
    # it means WhiteNoise failed to find it in the static directory.
    # We MUST NOT return index.html here, as the browser will try to parse 
    # the HTML as JS/CSS and crash the UI.
    if path_str and '.' in path_str and not path_str.endswith('.html'):
        logger.error(f"Static asset missing from WhiteNoise: {path_str}")
        raise Http404(f"Asset '{path_str}' not found in static storage.")

    # --- PATH RESOLUTION ---
    # 1. Try the Vite build directory (frontend/dist)
    # 2. Fallback to the collected static root (staticfiles)
    index_path = Path(settings.REACT_BUILD_DIR) / 'index.html'
    
    if not index_path.exists():
        index_path = Path(settings.STATIC_ROOT) / 'index.html'

    if not index_path.exists():
        logger.critical(f"FATAL: UI entry point missing. Expected at: {index_path}")
        # We return a 200 with a diagnostic message so DO health checks pass
        # but the developer sees exactly what is wrong.
        return HttpResponse(
            f"<h1>Deployment Error</h1><p>index.html not found at <code>{index_path}</code>. "
            f"Check if <code>npm run build</code> and <code>collectstatic</code> succeeded.</p>",
            status=200
        )

    try:
        with open(index_path, 'r', encoding='utf-8') as f:
            content = f.read()
            return HttpResponse(content, content_type="text/html")
    except Exception as e:
        logger.error(f"Error reading index.html: {str(e)}")
        return HttpResponse("Internal Server Error: Failed to load UI.", status=500)

def debug_prompt_view(request):
    """Utility view for debugging LLM prompts."""
    return render(request, 'debug_prompt.html')

def test_ui_view(request):
    """Utility view for testing UI components without React build."""
    return render(request, 'test_ui.html')