"""Convert the owner review CSV into the availability seed YAML.

The CSV (docs/ingredient-availability-review.csv) is the human surface: the
owner fills YOUR_TIER only where he disagrees. This produces the machine
surface that rate_ingredient_availability loads. Re-run it whenever more
rows get reviewed.
"""
import csv
from pathlib import Path

import yaml
from django.core.management.base import BaseCommand, CommandError

from diet_planner.models import Availability

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CSV = REPO_ROOT / 'docs' / 'ingredient-availability-review.csv'
DEFAULT_OUT = Path(__file__).resolve().parents[2] / 'data' / 'ingredient_availability.yaml'

VALID = {c for c in Availability.values if c != Availability.UNRATED}

HEADER = (
    "# GENERATED by `manage.py import_availability_review` — do not hand-edit.\n"
    "# Source of truth is docs/ingredient-availability-review.csv (owner review).\n"
    "# confidence: owner = arbitrated by the owner; low = Claude is guessing.\n"
)


class Command(BaseCommand):
    help = 'Convert the availability review CSV into data/ingredient_availability.yaml'

    def add_arguments(self, parser):
        parser.add_argument('--csv-file', dest='csv_file', default=str(DEFAULT_CSV))
        parser.add_argument('--out', dest='out', default=str(DEFAULT_OUT))

    def handle(self, *args, **options):
        csv_path = Path(options['csv_file'])
        if not csv_path.exists():
            raise CommandError(f'Review CSV not found: {csv_path}')

        rows = []
        with csv_path.open(encoding='utf-8-sig', newline='') as fh:
            for line in csv.DictReader(fh):
                slug = (line.get('slug') or '').strip()
                if not slug:
                    continue
                owner_tier = (line.get('YOUR_TIER') or '').strip().lower()
                claude_tier = (line.get('claude_tier') or '').strip().lower()
                tier = owner_tier or claude_tier
                if tier not in VALID:
                    raise CommandError(
                        f'{slug}: unknown tier {tier!r} '
                        f'(expected one of {sorted(VALID)})'
                    )
                note = (line.get('YOUR_NOTE') or '').strip() \
                    or (line.get('claude_note') or '').strip()
                rows.append({
                    'slug': slug,
                    'availability': tier,
                    'confidence': 'owner' if owner_tier else (
                        line.get('confidence') or 'high').strip(),
                    'note': note[:200],
                })

        rows.sort(key=lambda r: r['slug'])
        out_path = Path(options['out'])
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with out_path.open('w', encoding='utf-8') as fh:
            fh.write(HEADER)
            yaml.safe_dump(rows, fh, allow_unicode=True, sort_keys=False)

        owner = sum(1 for r in rows if r['confidence'] == 'owner')
        guess = sum(1 for r in rows if r['confidence'] == 'low')
        self.stdout.write(self.style.SUCCESS(
            f'wrote {len(rows)} ratings to {out_path} '
            f'(owner-settled={owner}, still-guessing={guess})'
        ))
