# Generated by Django 5.2.9 on 2026-01-07 19:01

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopifyStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the store", max_length=255
                    ),
                ),
                (
                    "store_domain",
                    models.CharField(
                        help_text="Shopify store domain (e.g., 'mealprep-9693.myshopify.com')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "storefront_access_token",
                    encrypted_model_fields.fields.EncryptedCharField(
                        help_text="Shopify Storefront API access token (encrypted)"
                    ),
                ),
                (
                    "admin_api_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True,
                        help_text="Shopify Admin API key (optional, for order management - encrypted)",
                        null=True,
                    ),
                ),
                (
                    "admin_api_secret",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True,
                        help_text="Shopify Admin API secret (optional - encrypted)",
                        null=True,
                    ),
                ),
                (
                    "webhook_secret",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True,
                        help_text="Webhook secret for verifying incoming webhooks (encrypted)",
                        null=True,
                    ),
                ),
                (
                    "meal_plan_variant_id",
                    models.CharField(
                        blank=True,
                        help_text="Shopify variant ID for the 'Meal Plan Generation' product",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this store configuration is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shopify Store",
                "verbose_name_plural": "Shopify Stores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShopifyProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        help_text="Shopify product ID (GraphQL GID)", max_length=255
                    ),
                ),
                (
                    "variant_id",
                    models.CharField(
                        help_text="Shopify product variant ID (GraphQL GID)",
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(help_text="Product title", max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Product price in store currency",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "available_for_sale",
                    models.BooleanField(
                        default=True, help_text="Whether product is currently available"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Product image URL",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "product_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full product data from Shopify API",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        help_text="Shopify store this product belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shopifyin.shopifystore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopify Product",
                "verbose_name_plural": "Shopify Products",
                "indexes": [
                    models.Index(
                        fields=["store", "available_for_sale"],
                        name="shopifyin_s_store_i_2fbaa5_idx",
                    ),
                    models.Index(
                        fields=["product_id"], name="shopifyin_s_product_e16360_idx"
                    ),
                ],
                "unique_together": {("store", "variant_id")},
            },
        ),
        migrations.CreateModel(
            name="ShopifyCheckout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checkout_id",
                    models.CharField(
                        help_text="Shopify checkout ID (e.g., 'gid://shopify/Checkout/...')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "checkout_token",
                    models.CharField(
                        help_text="Shopify checkout token for accessing checkout",
                        max_length=255,
                    ),
                ),
                (
                    "checkout_url",
                    models.URLField(
                        help_text="URL to redirect user to complete checkout",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending Payment"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        help_text="Current status of the checkout",
                        max_length=20,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total price in store currency",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (e.g., goal_id, product_ids)",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True,
                        help_text="Shopify order ID after checkout completion",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable order number",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When checkout was completed", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Django user who initiated the checkout",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopify_checkouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        help_text="Shopify store for this checkout",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkouts",
                        to="shopifyin.shopifystore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopify Checkout",
                "verbose_name_plural": "Shopify Checkouts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="shopifyin_s_user_id_f0d79a_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="shopifyin_s_status_f42acd_idx",
                    ),
                    models.Index(
                        fields=["checkout_token"], name="shopifyin_s_checkou_30688e_idx"
                    ),
                ],
            },
        ),
    ]
