# Generated by Django 5.2.9 on 2026-01-07 20:28

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopifyin", "0001_add_webhook_and_variant_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopifystore",
            name="meal_plan_variant_id",
            field=models.CharField(
                blank=True,
                help_text="Shopify Product Variant ID for the meal plan generation product (e.g., gid://shopify/ProductVariant/...)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shopifystore",
            name="webhook_secret",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                help_text="Shopify webhook secret for verifying webhook signatures (encrypted)",
                null=True,
            ),
        ),
    ]
