# Generated by Django 5.2.9 on 2026-01-02 16:41

import django.core.validators
import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietaryGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    encrypted_model_fields.fields.EncryptedTextField(
                        help_text="User's dietary prompt with goals/requirements (encrypted)"
                    ),
                ),
                (
                    "dietary_restrictions",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True,
                        help_text="Dietary restrictions or allergies (encrypted)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Processing status of the dietary goal",
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("DE", "Germany"),
                            ("PL", "Poland"),
                            ("CZ", "Czech Republic"),
                            ("SK", "Slovakia"),
                            ("HU", "Hungary"),
                            ("RO", "Romania"),
                            ("BG", "Bulgaria"),
                            ("AT", "Austria"),
                        ],
                        help_text="Country where user wants to buy ingredients",
                        max_length=2,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City where user wants to buy ingredients",
                        max_length=100,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("PLN", "Polish Złoty"),
                            ("CZK", "Czech Koruna"),
                            ("HUF", "Hungarian Forint"),
                            ("EUR", "Euro"),
                            ("RON", "Romanian Leu"),
                            ("BGN", "Bulgarian Lev"),
                        ],
                        default="PLN",
                        help_text="Currency for price calculations (auto-determined from country)",
                        max_length=3,
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        default="pl",
                        help_text="Language code (ISO 639-1) for i18n support",
                        max_length=5,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the goal was created (ISO-8601)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the goal was last updated (ISO-8601)",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When processing completed (ISO-8601)",
                        null=True,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for async processing",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this dietary goal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dietary_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DietaryPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_ideas",
                    models.JSONField(
                        default=list,
                        help_text="LLM-generated meal ideas and recipes (JSON structure)",
                    ),
                ),
                (
                    "shopping_list",
                    models.JSONField(
                        default=list,
                        help_text="LLM-generated shopping list with ingredients (JSON structure)",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total price calculated from database (not LLM guess)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="PLN",
                        help_text="Currency of the total price",
                        max_length=3,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the plan was generated (ISO-8601)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the plan was last updated (ISO-8601)",
                    ),
                ),
                (
                    "dietary_goal",
                    models.OneToOneField(
                        help_text="The dietary goal this plan fulfils",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dietary_plan",
                        to="diet_planner.dietarygoal",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dietarygoal",
            index=models.Index(
                fields=["user", "-created_at"], name="diet_planne_user_id_267b95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dietarygoal",
            index=models.Index(fields=["status"], name="diet_planne_status_d14f37_idx"),
        ),
        migrations.AddIndex(
            model_name="dietarygoal",
            index=models.Index(
                fields=["country"], name="diet_planne_country_f59cc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dietaryplan",
            index=models.Index(
                fields=["dietary_goal"], name="diet_planne_dietary_e18f95_idx"
            ),
        ),
    ]
