# Generated by Django 5.2.9 on 2026-01-02 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diet_planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietaryplan",
            name="llm_cost_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Cost of LLM API call in USD",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="dietaryplan",
            name="llm_input_tokens",
            field=models.IntegerField(
                blank=True, help_text="Number of input tokens used by LLM", null=True
            ),
        ),
        migrations.AddField(
            model_name="dietaryplan",
            name="llm_model_used",
            field=models.CharField(
                blank=True,
                help_text="OpenAI model used for generation (e.g., gpt-4o-mini)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dietaryplan",
            name="llm_output_tokens",
            field=models.IntegerField(
                blank=True, help_text="Number of output tokens used by LLM", null=True
            ),
        ),
        migrations.AddField(
            model_name="dietaryplan",
            name="llm_total_tokens",
            field=models.IntegerField(
                blank=True, help_text="Total tokens used by LLM", null=True
            ),
        ),
    ]
