# Generated by Django 5.2.9 on 2026-01-03 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diet_planner", "0002_dietaryplan_llm_cost_usd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietarygoal",
            name="main_courses_per_day",
            field=models.IntegerField(
                default=1,
                help_text="Number of main courses per day",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="dietarygoal",
            name="num_days",
            field=models.IntegerField(
                default=7,
                help_text="Number of days for the meal plan",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AddField(
            model_name="dietarygoal",
            name="small_meals_per_day",
            field=models.IntegerField(
                default=2,
                help_text="Number of small meals per day",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="dietarygoal",
            name="snacks_per_day",
            field=models.IntegerField(
                default=1,
                help_text="Number of snacks per day",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AddField(
            model_name="dietaryplan",
            name="days",
            field=models.JSONField(
                default=list,
                help_text="Day-by-day meal plan with main courses, small meals, and snacks (JSON structure)",
            ),
        ),
        migrations.AlterField(
            model_name="dietaryplan",
            name="meal_ideas",
            field=models.JSONField(
                default=list,
                help_text="Legacy field: meal ideas (deprecated, use days instead)",
            ),
        ),
    ]
