# Generated by Django 5.2.9 on 2026-01-03 22:33

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diet_planner", "0006_add_recipe_and_mealinstance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeafletOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop",
                    models.CharField(
                        choices=[
                            ("LIDL_CZ", "Lidl (Czech Republic)"),
                            ("ROHLIK", "Rohlik.cz"),
                            ("LIDL_SK", "Lidl (Slovakia)"),
                            ("LUNYS", "Lunys.sk"),
                        ],
                        help_text="Shop identifier",
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("DE", "Germany"),
                            ("PL", "Poland"),
                            ("CZ", "Czech Republic"),
                            ("SK", "Slovakia"),
                            ("HU", "Hungary"),
                            ("RO", "Romania"),
                            ("BG", "Bulgaria"),
                            ("AT", "Austria"),
                        ],
                        help_text="Country code",
                        max_length=2,
                    ),
                ),
                (
                    "ingredient_name",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized ingredient name (lowercase, for matching)",
                        max_length=255,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Original display name from source", max_length=255
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price (optional, for price matching later)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(help_text="Currency code", max_length=3)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement (kg, piece, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "scraped_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the offer was scraped (ISO-8601)",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the cached data expires (ISO-8601, typically scraped_at + 24h)",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Source URL (optional, for debugging)",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-scraped_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="mealinstance",
            new_name="diet_planne_user_id_f103bc_idx",
            old_name="diet_plann_mealinst_user_idx",
        ),
        migrations.RenameIndex(
            model_name="mealinstance",
            new_name="diet_planne_dietary_cb954e_idx",
            old_name="diet_plann_mealinst_goal_idx",
        ),
        migrations.RenameIndex(
            model_name="mealinstance",
            new_name="diet_planne_meal_id_cab95e_idx",
            old_name="diet_plann_mealinst_meal_id_idx",
        ),
        migrations.RenameIndex(
            model_name="mealinstance",
            new_name="diet_planne_is_cook_9053fb_idx",
            old_name="diet_plann_mealinst_cook_idx",
        ),
        migrations.RenameIndex(
            model_name="recipe",
            new_name="diet_planne_dietary_265df0_idx",
            old_name="diet_plann_recipe_goal_idx",
        ),
        migrations.RenameIndex(
            model_name="recipe",
            new_name="diet_planne_meal_id_261cb2_idx",
            old_name="diet_plann_recipe_meal_id_idx",
        ),
        migrations.AddField(
            model_name="dietarygoal",
            name="shop",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LIDL_CZ", "Lidl (Czech Republic)"),
                    ("ROHLIK", "Rohlik.cz"),
                    ("LIDL_SK", "Lidl (Slovakia)"),
                    ("LUNYS", "Lunys.sk"),
                ],
                help_text="Shop where user wants to source ingredients",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="dietarygoal",
            index=models.Index(
                fields=["country", "shop"], name="diet_planne_country_bb059e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leafletoffer",
            index=models.Index(
                fields=["shop", "country", "expires_at"],
                name="diet_planne_shop_0b87f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leafletoffer",
            index=models.Index(
                fields=["ingredient_name", "shop", "country"],
                name="diet_planne_ingredi_8b4771_idx",
            ),
        ),
    ]
