# Generated by Django 5.2.9 on 2026-01-04 15:39:34
# Empty migration to prevent Django from recreating RenameIndex operations
# The indexes in the database were created with names that don't match Django's
# auto-generated names, but they function correctly and don't need to be renamed.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diet_planner", "0007_leafletoffer_and_more"),
    ]

    operations = [
        # Empty operations list - indexes work fine with their current names
        # and don't need to be renamed. The original migration 0006 created
        # indexes with names like "diet_plann_recipe_goal_idx" which are
        # functionally identical to Django's preferred naming convention.
    ]

