# Generated by Django 5.2.9 on 2026-01-07 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "diet_planner",
            "0008_rename_diet_plann_mealinst_user_idx_diet_planne_user_id_f103bc_idx_and_more",
        ),
    ]

    operations = [
        # Note: Index renames removed - already handled by migration 0008
        migrations.AddField(
            model_name="dietarygoal",
            name="error_message",
            field=models.TextField(
                blank=True,
                help_text="User-friendly error message if generation failed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dietarygoal",
            name="is_free_generation",
            field=models.BooleanField(
                default=False,
                help_text="Whether this was a free generation (not charged)",
            ),
        ),
        migrations.AddField(
            model_name="dietarygoal",
            name="payment_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When payment was confirmed via webhook (ISO-8601)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dietarygoal",
            name="shopify_checkout_id",
            field=models.CharField(
                blank=True,
                help_text="Shopify checkout ID if payment required",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dietarygoal",
            name="validation_errors",
            field=models.JSONField(
                blank=True,
                help_text="List of validation errors if validation failed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dietarygoal",
            name="validation_passed",
            field=models.BooleanField(
                default=False, help_text="Whether the generated plan passed validation"
            ),
        ),
        migrations.AddField(
            model_name="leafletoffer",
            name="discount_percentage",
            field=models.IntegerField(
                blank=True,
                help_text="Discount percentage (for discounted items)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="leafletoffer",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original price before discount (for discounted items)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="leafletoffer",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("DISCOUNTED", "Discounted/Promotional"),
                    ("REGULAR", "Regular Price"),
                    ("LLM_ESTIMATED", "LLM Estimated"),
                ],
                default="REGULAR",
                help_text="Type of price (from leaflet promotion, regular, or estimated)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dietarygoal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("awaiting_payment", "Awaiting Payment"),
                    ("payment_confirmed", "Payment Confirmed"),
                    ("processing", "Processing"),
                    ("processing_meal_plan", "Generating Meal Plan"),
                    ("processing_shopping_list", "Creating Shopping List"),
                    ("validating", "Validating"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refund_eligible", "Refund Eligible"),
                ],
                default="pending",
                help_text="Processing status of the dietary goal",
                max_length=30,
            ),
        ),
    ]
