# Generated by Django 5.2.9 on 2026-01-07 20:29
# Note: Index names were already updated in previous migrations.
# This migration is a no-op to sync the migration state.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diet_planner", "0009_add_payment_and_price_type_fields"),
    ]

    operations = [
        # No operations needed - indexes already have correct names
    ]
