# Generated by Django 5.2.14 on 2026-05-26 17:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0015_backfill_food_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Canonical English name', max_length=255)),
                ('name_cs', models.CharField(blank=True, help_text='Czech name', max_length=255)),
                ('name_sk', models.CharField(blank=True, help_text='Slovak name', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('meat', 'Meat & Poultry'), ('fish', 'Fish & Seafood'), ('dairy', 'Dairy'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains & Cereals'), ('legumes', 'Legumes'), ('oils', 'Oils & Fats'), ('spices', 'Spices & Seasonings'), ('eggs', 'Eggs'), ('nuts', 'Nuts & Seeds'), ('beverages', 'Beverages'), ('condiments', 'Condiments & Sauces'), ('baking', 'Baking'), ('canned', 'Canned & Preserved'), ('frozen', 'Frozen'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('default_unit', models.CharField(default='g', max_length=10)),
                ('typical_unit', models.CharField(blank=True, max_length=10)),
                ('avg_piece_weight_g', models.DecimalField(blank=True, decimal_places=2, help_text='Average weight per piece for ks-based items', max_digits=8, null=True)),
                ('typical_package_sizes', models.JSONField(blank=True, default=list, help_text='Common package sizes, e.g. [250, 500, 1000]')),
                ('is_pantry_staple', models.BooleanField(db_index=True, default=False, help_text='Always available; does not require a store match')),
                ('estimated_price_czk', models.DecimalField(blank=True, decimal_places=2, help_text='Fallback estimated price in CZK for pantry staples', max_digits=8, null=True)),
                ('estimated_price_eur', models.DecimalField(blank=True, decimal_places=2, help_text='Fallback estimated price in EUR for pantry staples', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canonical Ingredient',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Machine identifier, e.g. LIDL_CZ, ALBERT_CZ', max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('chain', models.CharField(db_index=True, help_text='Chain family, e.g. LIDL, ALBERT, KAUFLAND', max_length=30)),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('currency', models.CharField(max_length=3)),
                ('website_url', models.URLField(blank=True)),
                ('scrape_url', models.URLField(blank=True)),
                ('is_online_only', models.BooleanField(default=False, help_text='True for delivery-only stores like Rohlik, Kosik')),
                ('is_active', models.BooleanField(default=True)),
                ('default_price_ttl_hours', models.IntegerField(default=168, help_text='Default hours before a price is considered stale')),
            ],
            options={
                'ordering': ['chain', 'country'],
            },
        ),
        migrations.CreateModel(
            name='IngredientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=255)),
                ('language_code', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Ingredient Aliases',
            },
        ),
        migrations.CreateModel(
            name='IngredientSubstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.DecimalField(decimal_places=2, default=Decimal('0.80'), help_text='1.0 = perfect substitute, 0.5 = acceptable', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('conversion_factor', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Multiply quantity by this when substituting', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PriceFreshnessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('LEAFLET_DISCOUNT', 'Leaflet/Promotional Discount'), ('STORE_REGULAR', 'Regular Store Price'), ('STORE_API', 'Store API/Catalog'), ('HISTORICAL_AVERAGE', 'Historical Average'), ('COMPETITOR_REFERENCE', 'Competitor Reference'), ('LLM_ESTIMATED', 'LLM Estimated'), ('USER_REPORTED', 'User-Reported')], max_length=25, unique=True)),
                ('ttl_hours', models.IntegerField(help_text='Hours before a price of this type is considered stale')),
                ('auto_expire', models.BooleanField(default=False, help_text='Auto-set valid_until when recording a price')),
                ('default_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=3)),
            ],
            options={
                'verbose_name_plural': 'Price Freshness Policies',
            },
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('source_type', models.CharField(choices=[('LEAFLET_DISCOUNT', 'Leaflet/Promotional Discount'), ('STORE_REGULAR', 'Regular Store Price'), ('STORE_API', 'Store API/Catalog'), ('HISTORICAL_AVERAGE', 'Historical Average'), ('COMPETITOR_REFERENCE', 'Competitor Reference'), ('LLM_ESTIMATED', 'LLM Estimated'), ('USER_REPORTED', 'User-Reported')], db_index=True, max_length=25)),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('scraped_at', models.DateTimeField()),
                ('source_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial (some errors)'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('method', models.CharField(choices=[('LLM', 'Gemini LLM extraction'), ('STRUCTURED', 'BeautifulSoup/CSS'), ('HYBRID', 'Structured + LLM fallback')], default='HYBRID', max_length=15)),
                ('products_found', models.IntegerField(default=0)),
                ('products_created', models.IntegerField(default=0)),
                ('products_updated', models.IntegerField(default=0)),
                ('prices_recorded', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('llm_input_tokens', models.IntegerField(default=0)),
                ('llm_output_tokens', models.IntegerField(default=0)),
                ('llm_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('source_urls', models.JSONField(default=list)),
                ('error_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('package_size', models.DecimalField(blank=True, decimal_places=2, help_text='Size of the package (e.g., 500 for 500g)', max_digits=10, null=True)),
                ('package_unit', models.CharField(blank=True, max_length=10)),
                ('unit_conversion_factor', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Base units of the canonical ingredient per 1 unit of this product', max_digits=10)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['store', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='mealinstance',
            new_name='dp_mealinst_user_idx',
            old_name='diet_plann_mealinst_user_idx',
        ),
        migrations.RenameIndex(
            model_name='mealinstance',
            new_name='dp_mealinst_goal_idx',
            old_name='diet_plann_mealinst_goal_idx',
        ),
        migrations.RenameIndex(
            model_name='mealinstance',
            new_name='dp_mealinst_mealid_idx',
            old_name='diet_plann_mealinst_meal_id_idx',
        ),
        migrations.RenameIndex(
            model_name='mealinstance',
            new_name='dp_mealinst_cooked_idx',
            old_name='diet_plann_mealinst_cook_idx',
        ),
        migrations.AddField(
            model_name='dietarygoal',
            name='store_mode',
            field=models.CharField(choices=[('single', 'Single Store'), ('mix_cost', 'Mix - Minimize Cost'), ('mix_trips', 'Mix - Minimize Trips')], default='single', help_text='Single store or cross-store optimization (premium)', max_length=20),
        ),
        migrations.AddField(
            model_name='leafletoffer',
            name='freshness_state',
            field=models.CharField(choices=[('fresh', 'Fresh'), ('stale', 'Stale'), ('expired', 'Expired')], db_index=True, default='fresh', max_length=10),
        ),
        migrations.AddField(
            model_name='leafletoffer',
            name='stale_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietarygoal',
            name='shop',
            field=models.CharField(blank=True, choices=[('LIDL_CZ', 'Lidl (Czech Republic)'), ('ROHLIK', 'Rohlik.cz'), ('LIDL_SK', 'Lidl (Slovakia)'), ('LUNYS', 'Lunys.sk'), ('ALBERT_CZ', 'Albert (Czech Republic)'), ('KAUFLAND_CZ', 'Kaufland (Czech Republic)'), ('KAUFLAND_SK', 'Kaufland (Slovakia)'), ('PENNY_CZ', 'Penny (Czech Republic)'), ('TESCO_CZ', 'Tesco (Czech Republic)'), ('KOSIK_CZ', 'Košík.cz')], help_text='Shop where user wants to source ingredients', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leafletoffer',
            name='shop',
            field=models.CharField(choices=[('LIDL_CZ', 'Lidl (Czech Republic)'), ('ROHLIK', 'Rohlik.cz'), ('LIDL_SK', 'Lidl (Slovakia)'), ('LUNYS', 'Lunys.sk'), ('ALBERT_CZ', 'Albert (Czech Republic)'), ('KAUFLAND_CZ', 'Kaufland (Czech Republic)'), ('KAUFLAND_SK', 'Kaufland (Slovakia)'), ('PENNY_CZ', 'Penny (Czech Republic)'), ('TESCO_CZ', 'Tesco (Czech Republic)'), ('KOSIK_CZ', 'Košík.cz')], help_text='Shop identifier', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.JSONField(default=list, help_text='Step-by-step cooking instructions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutritional_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='canonicalingredient',
            index=models.Index(fields=['category'], name='diet_planne_categor_a78fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalingredient',
            index=models.Index(fields=['is_pantry_staple'], name='diet_planne_is_pant_7a5dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='grocerystore',
            index=models.Index(fields=['country', 'is_active'], name='diet_planne_country_5e0aa6_idx'),
        ),
        migrations.AddField(
            model_name='dietarygoal',
            name='grocery_store',
            field=models.ForeignKey(blank=True, help_text='Grocery store FK (preferred over shop CharField)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dietary_goals', to='diet_planner.grocerystore'),
        ),
        migrations.AddField(
            model_name='ingredientalias',
            name='canonical_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='diet_planner.canonicalingredient'),
        ),
        migrations.AddField(
            model_name='ingredientsubstitute',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_by', to='diet_planner.canonicalingredient'),
        ),
        migrations.AddField(
            model_name='ingredientsubstitute',
            name='substitute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_for', to='diet_planner.canonicalingredient'),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_runs', to='diet_planner.grocerystore'),
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='scrape_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_records', to='diet_planner.scraperun'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='canonical_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_products', to='diet_planner.canonicalingredient'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='diet_planner.grocerystore'),
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='store_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='diet_planner.storeproduct'),
        ),
        migrations.AddField(
            model_name='leafletoffer',
            name='store_product',
            field=models.ForeignKey(blank=True, help_text='Link to StoreProduct in new catalog schema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaflet_offers', to='diet_planner.storeproduct'),
        ),
        migrations.AddIndex(
            model_name='leafletoffer',
            index=models.Index(fields=['freshness_state'], name='diet_planne_freshne_e4b87d_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientalias',
            index=models.Index(fields=['alias'], name='diet_planne_alias_ef279c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientalias',
            unique_together={('alias', 'language_code')},
        ),
        migrations.AddIndex(
            model_name='ingredientsubstitute',
            index=models.Index(fields=['ingredient'], name='diet_planne_ingredi_55b65b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientsubstitute',
            unique_together={('ingredient', 'substitute')},
        ),
        migrations.AddIndex(
            model_name='scraperun',
            index=models.Index(fields=['store', '-started_at'], name='diet_planne_store_i_bfe362_idx'),
        ),
        migrations.AddIndex(
            model_name='scraperun',
            index=models.Index(fields=['status'], name='diet_planne_status_0e391f_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['store', 'normalized_name'], name='diet_planne_store_i_adcced_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['store', 'canonical_ingredient'], name='diet_planne_store_i_8ddae0_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['canonical_ingredient', 'is_active'], name='diet_planne_canonic_e3e815_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storeproduct',
            unique_together={('store', 'normalized_name')},
        ),
        migrations.AddIndex(
            model_name='pricerecord',
            index=models.Index(fields=['store_product', '-scraped_at'], name='idx_price_product_latest'),
        ),
        migrations.AddIndex(
            model_name='pricerecord',
            index=models.Index(fields=['store_product', 'source_type', '-scraped_at'], name='idx_price_source_latest'),
        ),
        migrations.AddIndex(
            model_name='pricerecord',
            index=models.Index(fields=['store_product', 'valid_from'], name='idx_price_timeseries'),
        ),
        migrations.AddIndex(
            model_name='pricerecord',
            index=models.Index(fields=['valid_until', 'source_type'], name='idx_price_expiry'),
        ),
    ]
