# Generated by Django 5.2.14 on 2026-05-26

from decimal import Decimal
from django.db import migrations


GROCERY_STORES = [
    # Existing stores
    {'code': 'LIDL_CZ', 'name': 'Lidl (Czech Republic)', 'chain': 'LIDL', 'country': 'CZ', 'currency': 'CZK', 'website_url': 'https://www.lidl.cz/', 'scrape_url': 'https://www.kupi.cz/letaky/lidl', 'is_online_only': False, 'default_price_ttl_hours': 168},
    {'code': 'LIDL_SK', 'name': 'Lidl (Slovakia)', 'chain': 'LIDL', 'country': 'SK', 'currency': 'EUR', 'website_url': 'https://www.lidl.sk/', 'scrape_url': 'https://kupino.sk/lidl', 'is_online_only': False, 'default_price_ttl_hours': 168},
    {'code': 'ROHLIK', 'name': 'Rohlik.cz', 'chain': 'ROHLIK', 'country': 'CZ', 'currency': 'CZK', 'website_url': 'https://www.rohlik.cz/', 'scrape_url': 'https://www.rohlik.cz/cs/akcni-nabidka', 'is_online_only': True, 'default_price_ttl_hours': 24},
    {'code': 'LUNYS', 'name': 'Lunys.sk', 'chain': 'LUNYS', 'country': 'SK', 'currency': 'EUR', 'website_url': 'https://lunys.sk/', 'scrape_url': 'https://lunys.sk/akcie', 'is_online_only': True, 'default_price_ttl_hours': 24},
    # New stores
    {'code': 'ALBERT_CZ', 'name': 'Albert (Czech Republic)', 'chain': 'ALBERT', 'country': 'CZ', 'currency': 'CZK', 'website_url': 'https://www.albert.cz/', 'scrape_url': 'https://www.kupi.cz/letaky/albert', 'is_online_only': False, 'default_price_ttl_hours': 168},
    {'code': 'KAUFLAND_CZ', 'name': 'Kaufland (Czech Republic)', 'chain': 'KAUFLAND', 'country': 'CZ', 'currency': 'CZK', 'website_url': 'https://www.kaufland.cz/', 'scrape_url': 'https://www.kupi.cz/letaky/kaufland', 'is_online_only': False, 'default_price_ttl_hours': 168},
    {'code': 'KAUFLAND_SK', 'name': 'Kaufland (Slovakia)', 'chain': 'KAUFLAND', 'country': 'SK', 'currency': 'EUR', 'website_url': 'https://www.kaufland.sk/', 'scrape_url': 'https://kupino.sk/kaufland', 'is_online_only': False, 'default_price_ttl_hours': 168},
    {'code': 'PENNY_CZ', 'name': 'Penny (Czech Republic)', 'chain': 'PENNY', 'country': 'CZ', 'currency': 'CZK', 'website_url': 'https://www.penny.cz/', 'scrape_url': 'https://www.kupi.cz/letaky/penny-market', 'is_online_only': False, 'default_price_ttl_hours': 168},
    {'code': 'TESCO_CZ', 'name': 'Tesco (Czech Republic)', 'chain': 'TESCO', 'country': 'CZ', 'currency': 'CZK', 'website_url': 'https://www.tesco.cz/', 'scrape_url': 'https://www.kupi.cz/letaky/tesco', 'is_online_only': False, 'default_price_ttl_hours': 168},
    {'code': 'KOSIK_CZ', 'name': 'Kosik.cz', 'chain': 'KOSIK', 'country': 'CZ', 'currency': 'CZK', 'website_url': 'https://www.kosik.cz/', 'scrape_url': '', 'is_online_only': True, 'default_price_ttl_hours': 24},
]

FRESHNESS_POLICIES = [
    {'source_type': 'LEAFLET_DISCOUNT', 'ttl_hours': 168, 'auto_expire': True, 'default_confidence': Decimal('0.85')},
    {'source_type': 'STORE_REGULAR', 'ttl_hours': 720, 'auto_expire': False, 'default_confidence': Decimal('0.75')},
    {'source_type': 'STORE_API', 'ttl_hours': 24, 'auto_expire': True, 'default_confidence': Decimal('0.95')},
    {'source_type': 'HISTORICAL_AVERAGE', 'ttl_hours': 2160, 'auto_expire': False, 'default_confidence': Decimal('0.40')},
    {'source_type': 'COMPETITOR_REFERENCE', 'ttl_hours': 336, 'auto_expire': False, 'default_confidence': Decimal('0.30')},
    {'source_type': 'LLM_ESTIMATED', 'ttl_hours': 720, 'auto_expire': False, 'default_confidence': Decimal('0.20')},
    {'source_type': 'USER_REPORTED', 'ttl_hours': 336, 'auto_expire': False, 'default_confidence': Decimal('0.60')},
]


def seed_stores(apps, schema_editor):
    GroceryStore = apps.get_model('diet_planner', 'GroceryStore')
    for store_data in GROCERY_STORES:
        GroceryStore.objects.update_or_create(
            code=store_data['code'],
            defaults=store_data,
        )


def seed_freshness_policies(apps, schema_editor):
    PriceFreshnessPolicy = apps.get_model('diet_planner', 'PriceFreshnessPolicy')
    for policy_data in FRESHNESS_POLICIES:
        PriceFreshnessPolicy.objects.update_or_create(
            source_type=policy_data['source_type'],
            defaults=policy_data,
        )


def backfill_grocery_store_fk(apps, schema_editor):
    """Populate DietaryGoal.grocery_store FK from the shop CharField."""
    DietaryGoal = apps.get_model('diet_planner', 'DietaryGoal')
    GroceryStore = apps.get_model('diet_planner', 'GroceryStore')

    store_map = {s.code: s for s in GroceryStore.objects.all()}
    goals_to_update = []
    for goal in DietaryGoal.objects.filter(grocery_store__isnull=True, shop__isnull=False):
        store = store_map.get(goal.shop)
        if store:
            goal.grocery_store = store
            goals_to_update.append(goal)
    if goals_to_update:
        DietaryGoal.objects.bulk_update(goals_to_update, ['grocery_store'], batch_size=500)


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0016_multi_store_catalog_and_pricing'),
    ]

    operations = [
        migrations.RunPython(seed_stores, reverse_noop),
        migrations.RunPython(seed_freshness_policies, reverse_noop),
        migrations.RunPython(backfill_grocery_store_fk, reverse_noop),
    ]
