# Generated by Django 5.2.14 on 2026-05-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0017_seed_grocery_stores_and_freshness_policies'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mealinstance',
            new_name='dp_mealinst_user_idx',
            old_name='diet_plann_mealinst_user_idx',
        ),
        migrations.RenameIndex(
            model_name='mealinstance',
            new_name='dp_mealinst_goal_idx',
            old_name='diet_plann_mealinst_goal_idx',
        ),
        migrations.RenameIndex(
            model_name='mealinstance',
            new_name='dp_mealinst_mealid_idx',
            old_name='diet_plann_mealinst_meal_id_idx',
        ),
        migrations.RenameIndex(
            model_name='mealinstance',
            new_name='dp_mealinst_cooked_idx',
            old_name='diet_plann_mealinst_cook_idx',
        ),
        migrations.AddField(
            model_name='dietaryplan',
            name='discount_optimization',
            field=models.JSONField(blank=True, help_text='LLM-suggested discount-based ingredient swaps with before/after comparison', null=True),
        ),
        migrations.AddField(
            model_name='dietaryplan',
            name='discount_optimization_applied',
            field=models.BooleanField(default=False, help_text='Whether the user has accepted and applied discount optimization'),
        ),
    ]
