# Generated by Django 5.2.14 on 2026-05-27 07:12

from django.db import migrations, models


def rename_indexes_if_exist(apps, schema_editor):
    """Rename old auto-truncated index names to new explicit names, skipping any that don't exist."""
    renames = [
        ('diet_plann_mealinst_user_idx', 'dp_mealinst_user_idx'),
        ('diet_plann_mealinst_goal_idx', 'dp_mealinst_goal_idx'),
        ('diet_plann_mealinst_meal_id_idx', 'dp_mealinst_mealid_idx'),
        ('diet_plann_mealinst_cook_idx', 'dp_mealinst_cooked_idx'),
    ]
    with schema_editor.connection.cursor() as cursor:
        for old_name, new_name in renames:
            cursor.execute(
                "SELECT 1 FROM pg_indexes WHERE indexname = %s", [old_name]
            )
            if cursor.fetchone():
                cursor.execute(
                    f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"'
                )


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0017_seed_grocery_stores_and_freshness_policies'),
    ]

    operations = [
        migrations.RunPython(rename_indexes_if_exist, migrations.RunPython.noop),
        migrations.AddField(
            model_name='dietaryplan',
            name='discount_optimization',
            field=models.JSONField(blank=True, help_text='LLM-suggested discount-based ingredient swaps with before/after comparison', null=True),
        ),
        migrations.AddField(
            model_name='dietaryplan',
            name='discount_optimization_applied',
            field=models.BooleanField(default=False, help_text='Whether the user has accepted and applied discount optimization'),
        ),
    ]
