# Generated by Django 5.2.14 on 2026-05-27 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rename_indexes_if_exist(apps, schema_editor):
    """Rename old auto-truncated index names to new explicit names, skipping any that don't exist."""
    renames = [
        ('diet_plann_mealinst_user_idx', 'dp_mealinst_user_idx'),
        ('diet_plann_mealinst_goal_idx', 'dp_mealinst_goal_idx'),
        ('diet_plann_mealinst_meal_id_idx', 'dp_mealinst_mealid_idx'),
        ('diet_plann_mealinst_cook_idx', 'dp_mealinst_cooked_idx'),
    ]
    with schema_editor.connection.cursor() as cursor:
        for old_name, new_name in renames:
            cursor.execute(
                "SELECT 1 FROM pg_indexes WHERE indexname = %s", [old_name]
            )
            if cursor.fetchone():
                cursor.execute(
                    f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"'
                )


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0018_discount_optimization_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # State+DB split: update Django's model state to know the indexes have
        # new names (so future `makemigrations` stops re-emitting RenameIndex
        # ops), while doing the actual rename conditionally — prod DB may
        # already have the new names from prior 0016/0018 RunPython renames,
        # or may have been initialised without these indexes at all.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='mealinstance',
                    new_name='dp_mealinst_user_idx',
                    old_name='diet_plann_mealinst_user_idx',
                ),
                migrations.RenameIndex(
                    model_name='mealinstance',
                    new_name='dp_mealinst_goal_idx',
                    old_name='diet_plann_mealinst_goal_idx',
                ),
                migrations.RenameIndex(
                    model_name='mealinstance',
                    new_name='dp_mealinst_mealid_idx',
                    old_name='diet_plann_mealinst_meal_id_idx',
                ),
                migrations.RenameIndex(
                    model_name='mealinstance',
                    new_name='dp_mealinst_cooked_idx',
                    old_name='diet_plann_mealinst_cook_idx',
                ),
            ],
            database_operations=[
                migrations.RunPython(rename_indexes_if_exist, migrations.RunPython.noop),
            ],
        ),
        migrations.AddField(
            model_name='pricefeedback',
            name='dietary_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_feedbacks', to='diet_planner.dietaryplan'),
        ),
        migrations.AddField(
            model_name='pricefeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
