# Generated by Django 5.2.14 on 2026-05-27 20:55

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet_planner", "0019_add_price_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicnutritionplan",
            name="extracted_text",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True,
                default="",
                help_text="Raw text extracted from PDF (encrypted)",
            ),
        ),
        migrations.AddField(
            model_name="historicnutritionplan",
            name="pdf_file",
            field=models.BinaryField(
                blank=True, help_text="Raw PDF bytes stored in PostgreSQL", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicnutritionplan",
            name="pdf_filename",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Original uploaded filename",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="historicnutritionplan",
            name="pdf_size_bytes",
            field=models.PositiveIntegerField(
                blank=True, help_text="PDF file size in bytes", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicnutritionplan",
            name="processing_error",
            field=models.TextField(
                blank=True, default="", help_text="Error message if processing failed"
            ),
        ),
        migrations.AddField(
            model_name="historicnutritionplan",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="PDF processing status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicnutritionplan",
            name="structured_constraints",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True,
                default="",
                help_text="Gemini-summarized JSON of dietary constraints (encrypted)",
            ),
        ),
        migrations.AlterField(
            model_name="historicnutritionplan",
            name="content",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True,
                default="",
                help_text="The actual clinical document or past plan text (encrypted)",
            ),
        ),
    ]
