# Generated by Claude on 2026-05-28
"""
Seed CanonicalIngredient rows for pantry staples plus IngredientAlias variants.

Staples are items bought in bulk and used in marginal amounts per recipe
(oils, vinegars, salt, dried spices, common bottled condiments, baking dry
goods). Flagged with is_pantry_staple=True so the pricing pipeline can
pro-rate by fraction actually consumed instead of charging the full pack.

Estimated prices are rough CZ/SK retail medians for a "typical" pack and
serve as fallbacks when no matched store product is found.
"""
from decimal import Decimal
from django.db import migrations
from django.utils.text import slugify


# Schema per row:
#   name (EN), name_cs, name_sk, category, default_unit,
#   typical_package_sizes (list), est_czk, est_eur,
#   aliases: list of (alias, language_code) tuples for variants the LLM
#   might emit that aren't already covered by name/name_cs/name_sk.
STAPLES = [
    # --- Oils & fats ---
    {
        'name': 'Olive oil', 'name_cs': 'Olivový olej', 'name_sk': 'Olivový olej',
        'category': 'oils', 'default_unit': 'ml',
        'typical_package_sizes': [250, 500, 750, 1000],
        'est_czk': '150.00', 'est_eur': '6.00',
        'aliases': [('extra virgin olive oil', 'en'), ('evoo', 'en'), ('extra panenský olivový olej', 'cs')],
    },
    {
        'name': 'Sunflower oil', 'name_cs': 'Slunečnicový olej', 'name_sk': 'Slnečnicový olej',
        'category': 'oils', 'default_unit': 'ml',
        'typical_package_sizes': [500, 1000],
        'est_czk': '50.00', 'est_eur': '2.00',
        'aliases': [('vegetable oil', 'en'), ('rostlinný olej', 'cs'), ('rastlinný olej', 'sk')],
    },
    {
        'name': 'Rapeseed oil', 'name_cs': 'Řepkový olej', 'name_sk': 'Repkový olej',
        'category': 'oils', 'default_unit': 'ml',
        'typical_package_sizes': [500, 1000],
        'est_czk': '50.00', 'est_eur': '2.00',
        'aliases': [('canola oil', 'en')],
    },
    {
        'name': 'Coconut oil', 'name_cs': 'Kokosový olej', 'name_sk': 'Kokosový olej',
        'category': 'oils', 'default_unit': 'ml',
        'typical_package_sizes': [200, 500],
        'est_czk': '120.00', 'est_eur': '5.00',
        'aliases': [],
    },
    {
        'name': 'Sesame oil', 'name_cs': 'Sezamový olej', 'name_sk': 'Sezamový olej',
        'category': 'oils', 'default_unit': 'ml',
        'typical_package_sizes': [100, 250],
        'est_czk': '100.00', 'est_eur': '4.00',
        'aliases': [],
    },
    {
        'name': 'Ghee', 'name_cs': 'Přepuštěné máslo', 'name_sk': 'Prepustené maslo',
        'category': 'oils', 'default_unit': 'g',
        'typical_package_sizes': [200, 250],
        'est_czk': '120.00', 'est_eur': '5.00',
        'aliases': [('clarified butter', 'en')],
    },

    # --- Vinegars ---
    {
        'name': 'White vinegar', 'name_cs': 'Bílý ocet', 'name_sk': 'Biely ocot',
        'category': 'condiments', 'default_unit': 'ml',
        'typical_package_sizes': [500, 1000],
        'est_czk': '20.00', 'est_eur': '0.80',
        'aliases': [('distilled vinegar', 'en'), ('kvasný ocet', 'cs')],
    },
    {
        'name': 'Apple cider vinegar', 'name_cs': 'Jablečný ocet', 'name_sk': 'Jablčný ocot',
        'category': 'condiments', 'default_unit': 'ml',
        'typical_package_sizes': [500, 750],
        'est_czk': '50.00', 'est_eur': '2.00',
        'aliases': [('cider vinegar', 'en'), ('acv', 'en')],
    },
    {
        'name': 'Balsamic vinegar', 'name_cs': 'Balzamikový ocet', 'name_sk': 'Balzamikový ocot',
        'category': 'condiments', 'default_unit': 'ml',
        'typical_package_sizes': [250, 500],
        'est_czk': '80.00', 'est_eur': '3.20',
        'aliases': [('balsamico', 'en')],
    },
    {
        'name': 'Rice vinegar', 'name_cs': 'Rýžový ocet', 'name_sk': 'Ryžový ocot',
        'category': 'condiments', 'default_unit': 'ml',
        'typical_package_sizes': [150, 250],
        'est_czk': '60.00', 'est_eur': '2.40',
        'aliases': [],
    },
    {
        'name': 'Wine vinegar', 'name_cs': 'Vinný ocet', 'name_sk': 'Vínový ocot',
        'category': 'condiments', 'default_unit': 'ml',
        'typical_package_sizes': [500, 750],
        'est_czk': '35.00', 'est_eur': '1.40',
        'aliases': [('red wine vinegar', 'en'), ('white wine vinegar', 'en')],
    },

    # --- Salt & pepper ---
    {
        'name': 'Table salt', 'name_cs': 'Kuchyňská sůl', 'name_sk': 'Kuchynská soľ',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [500, 1000],
        'est_czk': '10.00', 'est_eur': '0.40',
        'aliases': [('salt', 'en'), ('sůl', 'cs'), ('soľ', 'sk'), ('jodovaná sůl', 'cs')],
    },
    {
        'name': 'Sea salt', 'name_cs': 'Mořská sůl', 'name_sk': 'Morská soľ',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [250, 500],
        'est_czk': '25.00', 'est_eur': '1.00',
        'aliases': [('himalayan salt', 'en'), ('himalájská sůl', 'cs')],
    },
    {
        'name': 'Black pepper', 'name_cs': 'Mletý černý pepř', 'name_sk': 'Mleté čierne korenie',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [50, 100],
        'est_czk': '50.00', 'est_eur': '2.00',
        'aliases': [('pepper', 'en'), ('ground black pepper', 'en'), ('pepř', 'cs'), ('korenie', 'sk')],
    },
    {
        'name': 'White pepper', 'name_cs': 'Mletý bílý pepř', 'name_sk': 'Mleté biele korenie',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [25, 50],
        'est_czk': '60.00', 'est_eur': '2.40',
        'aliases': [],
    },

    # --- Dried spices & herbs ---
    {
        'name': 'Sweet paprika', 'name_cs': 'Sladká paprika', 'name_sk': 'Sladká paprika',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [25, 50, 100],
        'est_czk': '30.00', 'est_eur': '1.20',
        'aliases': [('paprika', 'en'), ('ground paprika', 'en'), ('mletá paprika', 'cs')],
    },
    {
        'name': 'Hot paprika', 'name_cs': 'Pálivá paprika', 'name_sk': 'Pálivá paprika',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [25, 50],
        'est_czk': '30.00', 'est_eur': '1.20',
        'aliases': [],
    },
    {
        'name': 'Smoked paprika', 'name_cs': 'Uzená paprika', 'name_sk': 'Údená paprika',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [25, 50],
        'est_czk': '50.00', 'est_eur': '2.00',
        'aliases': [],
    },
    {
        'name': 'Cumin', 'name_cs': 'Římský kmín', 'name_sk': 'Rímska rasca',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [25, 50],
        'est_czk': '25.00', 'est_eur': '1.00',
        'aliases': [('ground cumin', 'en')],
    },
    {
        'name': 'Caraway seeds', 'name_cs': 'Kmín', 'name_sk': 'Rasca',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [25, 50],
        'est_czk': '25.00', 'est_eur': '1.00',
        'aliases': [('caraway', 'en')],
    },
    {
        'name': 'Oregano', 'name_cs': 'Oregano', 'name_sk': 'Oregano',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [10, 20],
        'est_czk': '25.00', 'est_eur': '1.00',
        'aliases': [('dried oregano', 'en')],
    },
    {
        'name': 'Basil', 'name_cs': 'Sušená bazalka', 'name_sk': 'Sušená bazalka',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [10, 20],
        'est_czk': '25.00', 'est_eur': '1.00',
        'aliases': [('dried basil', 'en'), ('bazalka', 'cs')],
    },
    {
        'name': 'Thyme', 'name_cs': 'Tymián', 'name_sk': 'Tymián',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [10, 20],
        'est_czk': '25.00', 'est_eur': '1.00',
        'aliases': [('dried thyme', 'en')],
    },
    {
        'name': 'Rosemary', 'name_cs': 'Rozmarýn', 'name_sk': 'Rozmarín',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [10, 20],
        'est_czk': '25.00', 'est_eur': '1.00',
        'aliases': [('dried rosemary', 'en')],
    },
    {
        'name': 'Bay leaves', 'name_cs': 'Bobkový list', 'name_sk': 'Bobkový list',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [5, 10],
        'est_czk': '20.00', 'est_eur': '0.80',
        'aliases': [('bay leaf', 'en')],
    },
    {
        'name': 'Cinnamon', 'name_cs': 'Mletá skořice', 'name_sk': 'Mletá škorica',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [25, 50],
        'est_czk': '30.00', 'est_eur': '1.20',
        'aliases': [('ground cinnamon', 'en'), ('skořice', 'cs'), ('škorica', 'sk')],
    },
    {
        'name': 'Nutmeg', 'name_cs': 'Muškátový oříšek', 'name_sk': 'Muškátový oriešok',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [15, 30],
        'est_czk': '40.00', 'est_eur': '1.60',
        'aliases': [('ground nutmeg', 'en')],
    },
    {
        'name': 'Turmeric', 'name_cs': 'Kurkuma', 'name_sk': 'Kurkuma',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [25, 50],
        'est_czk': '30.00', 'est_eur': '1.20',
        'aliases': [('ground turmeric', 'en')],
    },
    {
        'name': 'Ground ginger', 'name_cs': 'Mletý zázvor', 'name_sk': 'Mletý ďumbier',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [25, 50],
        'est_czk': '35.00', 'est_eur': '1.40',
        'aliases': [('ginger powder', 'en')],
    },
    {
        'name': 'Chili powder', 'name_cs': 'Mletá chilli', 'name_sk': 'Mletá chilli',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [25, 50],
        'est_czk': '30.00', 'est_eur': '1.20',
        'aliases': [('chilli powder', 'en'), ('chilli', 'en')],
    },
    {
        'name': 'Cayenne pepper', 'name_cs': 'Kajenský pepř', 'name_sk': 'Kajenské korenie',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [25, 50],
        'est_czk': '35.00', 'est_eur': '1.40',
        'aliases': [('cayenne', 'en')],
    },
    {
        'name': 'Curry powder', 'name_cs': 'Kari koření', 'name_sk': 'Karí korenie',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [25, 50],
        'est_czk': '30.00', 'est_eur': '1.20',
        'aliases': [('curry', 'en'), ('kari', 'cs')],
    },
    {
        'name': 'Garlic powder', 'name_cs': 'Česnekový prášek', 'name_sk': 'Cesnakový prášok',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [25, 50],
        'est_czk': '35.00', 'est_eur': '1.40',
        'aliases': [('granulated garlic', 'en'), ('sušený česnek', 'cs')],
    },
    {
        'name': 'Onion powder', 'name_cs': 'Cibulový prášek', 'name_sk': 'Cibuľový prášok',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [25, 50],
        'est_czk': '30.00', 'est_eur': '1.20',
        'aliases': [('sušená cibule', 'cs')],
    },
    {
        'name': 'Ground coriander', 'name_cs': 'Mletý koriandr', 'name_sk': 'Mletý koriander',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [25, 50],
        'est_czk': '30.00', 'est_eur': '1.20',
        'aliases': [('coriander', 'en')],
    },

    # --- Condiments & bottled sauces ---
    {
        'name': 'Soy sauce', 'name_cs': 'Sójová omáčka', 'name_sk': 'Sójová omáčka',
        'category': 'condiments', 'default_unit': 'ml',
        'typical_package_sizes': [150, 250, 500],
        'est_czk': '50.00', 'est_eur': '2.00',
        'aliases': [('soya sauce', 'en'), ('shoyu', 'en')],
    },
    {
        'name': 'Dijon mustard', 'name_cs': 'Dijonská hořčice', 'name_sk': 'Dijonská horčica',
        'category': 'condiments', 'default_unit': 'g',
        'typical_package_sizes': [200, 250],
        'est_czk': '50.00', 'est_eur': '2.00',
        'aliases': [],
    },
    {
        'name': 'Yellow mustard', 'name_cs': 'Plnotučná hořčice', 'name_sk': 'Plnotučná horčica',
        'category': 'condiments', 'default_unit': 'g',
        'typical_package_sizes': [200, 300, 400],
        'est_czk': '30.00', 'est_eur': '1.20',
        'aliases': [('mustard', 'en'), ('hořčice', 'cs'), ('horčica', 'sk')],
    },
    {
        'name': 'Honey', 'name_cs': 'Med', 'name_sk': 'Med',
        'category': 'other', 'default_unit': 'g',
        'typical_package_sizes': [250, 500, 900],
        'est_czk': '100.00', 'est_eur': '4.00',
        'aliases': [('květový med', 'cs'), ('kvetový med', 'sk')],
    },
    {
        'name': 'Ketchup', 'name_cs': 'Kečup', 'name_sk': 'Kečup',
        'category': 'condiments', 'default_unit': 'g',
        'typical_package_sizes': [300, 500, 900],
        'est_czk': '40.00', 'est_eur': '1.60',
        'aliases': [('tomato ketchup', 'en')],
    },
    {
        'name': 'Worcestershire sauce', 'name_cs': 'Worcesterová omáčka', 'name_sk': 'Worcesterová omáčka',
        'category': 'condiments', 'default_unit': 'ml',
        'typical_package_sizes': [150, 250],
        'est_czk': '50.00', 'est_eur': '2.00',
        'aliases': [('worcester sauce', 'en')],
    },
    {
        'name': 'Tabasco sauce', 'name_cs': 'Tabasco', 'name_sk': 'Tabasco',
        'category': 'condiments', 'default_unit': 'ml',
        'typical_package_sizes': [60, 150],
        'est_czk': '100.00', 'est_eur': '4.00',
        'aliases': [('hot sauce', 'en'), ('tabasco', 'en')],
    },
    {
        'name': 'Sriracha sauce', 'name_cs': 'Sriracha omáčka', 'name_sk': 'Sriracha omáčka',
        'category': 'condiments', 'default_unit': 'ml',
        'typical_package_sizes': [200, 500],
        'est_czk': '90.00', 'est_eur': '3.60',
        'aliases': [('sriracha', 'en')],
    },
    {
        'name': 'Fish sauce', 'name_cs': 'Rybí omáčka', 'name_sk': 'Rybacia omáčka',
        'category': 'condiments', 'default_unit': 'ml',
        'typical_package_sizes': [200, 500],
        'est_czk': '80.00', 'est_eur': '3.20',
        'aliases': [('nam pla', 'en')],
    },
    {
        'name': 'Oyster sauce', 'name_cs': 'Ústřicová omáčka', 'name_sk': 'Ustricová omáčka',
        'category': 'condiments', 'default_unit': 'ml',
        'typical_package_sizes': [250, 500],
        'est_czk': '70.00', 'est_eur': '2.80',
        'aliases': [],
    },
    {
        'name': 'BBQ sauce', 'name_cs': 'BBQ omáčka', 'name_sk': 'BBQ omáčka',
        'category': 'condiments', 'default_unit': 'g',
        'typical_package_sizes': [300, 500],
        'est_czk': '60.00', 'est_eur': '2.40',
        'aliases': [('barbecue sauce', 'en')],
    },
    {
        'name': 'Tomato paste', 'name_cs': 'Rajčatový protlak', 'name_sk': 'Paradajkový pretlak',
        'category': 'condiments', 'default_unit': 'g',
        'typical_package_sizes': [70, 140, 200],
        'est_czk': '25.00', 'est_eur': '1.00',
        'aliases': [('tomato puree', 'en'), ('rajčatové pyré', 'cs')],
    },
    {
        'name': 'Maple syrup', 'name_cs': 'Javorový sirup', 'name_sk': 'Javorový sirup',
        'category': 'other', 'default_unit': 'ml',
        'typical_package_sizes': [250, 500],
        'est_czk': '200.00', 'est_eur': '8.00',
        'aliases': [],
    },

    # --- Baking & dry goods ---
    {
        'name': 'Plain flour', 'name_cs': 'Hladká mouka', 'name_sk': 'Hladká múka',
        'category': 'baking', 'default_unit': 'g',
        'typical_package_sizes': [1000, 2000],
        'est_czk': '25.00', 'est_eur': '1.00',
        'aliases': [('flour', 'en'), ('all-purpose flour', 'en'), ('mouka', 'cs'), ('múka', 'sk')],
    },
    {
        'name': 'White sugar', 'name_cs': 'Cukr krystal', 'name_sk': 'Cukor kryštál',
        'category': 'baking', 'default_unit': 'g',
        'typical_package_sizes': [500, 1000],
        'est_czk': '25.00', 'est_eur': '1.00',
        'aliases': [('sugar', 'en'), ('granulated sugar', 'en'), ('cukr', 'cs'), ('cukor', 'sk')],
    },
    {
        'name': 'Brown sugar', 'name_cs': 'Třtinový cukr', 'name_sk': 'Trstinový cukor',
        'category': 'baking', 'default_unit': 'g',
        'typical_package_sizes': [500, 1000],
        'est_czk': '50.00', 'est_eur': '2.00',
        'aliases': [('cane sugar', 'en')],
    },
    {
        'name': 'Powdered sugar', 'name_cs': 'Cukr moučka', 'name_sk': 'Práškový cukor',
        'category': 'baking', 'default_unit': 'g',
        'typical_package_sizes': [200, 500],
        'est_czk': '25.00', 'est_eur': '1.00',
        'aliases': [('icing sugar', 'en'), ('confectioners sugar', 'en')],
    },
    {
        'name': 'Baking powder', 'name_cs': 'Kypřící prášek', 'name_sk': 'Prášok do pečiva',
        'category': 'baking', 'default_unit': 'g',
        'typical_package_sizes': [12, 36],
        'est_czk': '5.00', 'est_eur': '0.20',
        'aliases': [('prášek do pečiva', 'cs')],
    },
    {
        'name': 'Baking soda', 'name_cs': 'Jedlá soda', 'name_sk': 'Jedlá sóda',
        'category': 'baking', 'default_unit': 'g',
        'typical_package_sizes': [50, 100],
        'est_czk': '15.00', 'est_eur': '0.60',
        'aliases': [('sodium bicarbonate', 'en'), ('bicarbonate of soda', 'en')],
    },
    {
        'name': 'Dry yeast', 'name_cs': 'Sušené droždí', 'name_sk': 'Sušené droždie',
        'category': 'baking', 'default_unit': 'g',
        'typical_package_sizes': [7, 21],
        'est_czk': '10.00', 'est_eur': '0.40',
        'aliases': [('instant yeast', 'en'), ('active dry yeast', 'en')],
    },
    {
        'name': 'Cornstarch', 'name_cs': 'Kukuřičný škrob', 'name_sk': 'Kukuričný škrob',
        'category': 'baking', 'default_unit': 'g',
        'typical_package_sizes': [200, 400],
        'est_czk': '30.00', 'est_eur': '1.20',
        'aliases': [('corn starch', 'en'), ('maizena', 'en')],
    },
    {
        'name': 'Cocoa powder', 'name_cs': 'Kakaový prášek', 'name_sk': 'Kakaový prášok',
        'category': 'baking', 'default_unit': 'g',
        'typical_package_sizes': [100, 200],
        'est_czk': '40.00', 'est_eur': '1.60',
        'aliases': [('cocoa', 'en'), ('kakao', 'cs')],
    },
    {
        'name': 'Vanilla extract', 'name_cs': 'Vanilkový extrakt', 'name_sk': 'Vanilkový extrakt',
        'category': 'baking', 'default_unit': 'ml',
        'typical_package_sizes': [30, 50],
        'est_czk': '60.00', 'est_eur': '2.40',
        'aliases': [('vanilla', 'en'), ('vanilkový cukr', 'cs')],
    },

    # --- CZ/SK-specific staples ---
    {
        'name': 'Vegeta seasoning', 'name_cs': 'Vegeta', 'name_sk': 'Vegeta',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [125, 250, 500],
        'est_czk': '50.00', 'est_eur': '2.00',
        'aliases': [('vegeta', 'en')],
    },
    {
        'name': 'Stock cube', 'name_cs': 'Bujón v kostce', 'name_sk': 'Bujón v kocke',
        'category': 'spices', 'default_unit': 'g',
        'typical_package_sizes': [60, 120],
        'est_czk': '30.00', 'est_eur': '1.20',
        'aliases': [('bouillon cube', 'en'), ('broth cube', 'en'), ('bujon', 'cs')],
    },
    {
        'name': 'Horseradish', 'name_cs': 'Strouhaný křen', 'name_sk': 'Strúhaný chren',
        'category': 'condiments', 'default_unit': 'g',
        'typical_package_sizes': [180, 300],
        'est_czk': '40.00', 'est_eur': '1.60',
        'aliases': [('křen', 'cs'), ('chren', 'sk')],
    },
    {
        'name': 'Potato starch', 'name_cs': 'Bramborový škrob', 'name_sk': 'Zemiakový škrob',
        'category': 'baking', 'default_unit': 'g',
        'typical_package_sizes': [200, 500],
        'est_czk': '25.00', 'est_eur': '1.00',
        'aliases': [('potato flour', 'en'), ('solamyl', 'cs')],
    },
]


def seed_canonical_staples(apps, schema_editor):
    CanonicalIngredient = apps.get_model('diet_planner', 'CanonicalIngredient')
    IngredientAlias = apps.get_model('diet_planner', 'IngredientAlias')

    for row in STAPLES:
        slug = slugify(row['name'])[:255]
        ci, _ = CanonicalIngredient.objects.update_or_create(
            slug=slug,
            defaults={
                'name': row['name'],
                'name_cs': row['name_cs'],
                'name_sk': row['name_sk'],
                'category': row['category'],
                'default_unit': row['default_unit'],
                'typical_unit': row['default_unit'],
                'typical_package_sizes': row['typical_package_sizes'],
                'is_pantry_staple': True,
                'estimated_price_czk': Decimal(row['est_czk']),
                'estimated_price_eur': Decimal(row['est_eur']),
            },
        )
        for alias_text, lang in row.get('aliases', []):
            IngredientAlias.objects.update_or_create(
                alias=alias_text.lower(),
                language_code=lang,
                defaults={'canonical_ingredient': ci},
            )


def unseed_canonical_staples(apps, schema_editor):
    CanonicalIngredient = apps.get_model('diet_planner', 'CanonicalIngredient')
    slugs = [slugify(row['name'])[:255] for row in STAPLES]
    # CASCADE removes IngredientAlias rows tied to these canonical ingredients.
    CanonicalIngredient.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0020_historic_plan_pdf_fields'),
    ]

    operations = [
        migrations.RunPython(seed_canonical_staples, unseed_canonical_staples),
    ]
