# Generated by Django 5.2.14 on 2026-05-28 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0022_seed_canonical_staples'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryplan',
            name='pantry_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pro-rated share of pantry staples included in total_price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
