# Generated by Claude on 2026-05-28
"""
Point the default django.contrib.sites Site row at the production
custom domain so absolute URLs (sitemaps, password reset emails,
allauth confirmation links, etc.) resolve to eatalnicek.eu instead
of the legacy example.com / *.ondigitalocean.app values.
"""
from django.db import migrations


NEW_DOMAIN = "eatalnicek.eu"
NEW_NAME = "DietPlanner AI"


def forwards(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    Site.objects.update_or_create(
        id=1,
        defaults={"domain": NEW_DOMAIN, "name": NEW_NAME},
    )


def backwards(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    Site.objects.update_or_create(
        id=1,
        defaults={"domain": "example.com", "name": "example.com"},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("diet_planner", "0023_add_dietaryplan_pantry_price"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
