# Generated by Django 5.2.14 on 2026-05-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0024_update_site_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryplan',
            name='pantry_basics_on',
            field=models.BooleanField(default=True, help_text='User has dry basics (salt, oil, spices, ...) at home; exclude from price range'),
        ),
        migrations.AddField(
            model_name='dietaryplan',
            name='pantry_fridge_on',
            field=models.BooleanField(default=False, help_text='User has fridge basics (milk, butter, eggs) at home; exclude from price range'),
        ),
    ]
