# Generated by Django 5.2.14 on 2026-06-11 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0025_dietaryplan_pantry_basics_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name_cs', models.CharField(help_text='Czech dish name (real, named dish)', max_length=255)),
                ('name_en', models.CharField(blank=True, help_text='Optional English gloss', max_length=255)),
                ('description', models.TextField(blank=True, help_text='1-2 appetizing sentences in Czech')),
                ('meal_types', models.JSONField(default=list, help_text='Slots this can fill: breakfast/lunch/dinner/snack/small_meal')),
                ('cuisine', models.CharField(blank=True, db_index=True, help_text='czech/italian/asian/mediterranean/... — for variety + soft ranking, not a filter', max_length=40)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium')], db_index=True, default='easy', max_length=10)),
                ('dietary_tags', models.JSONField(default=list, help_text='vegetarian, vegan, gluten_free, dairy_free, high_protein, low_carb, ...')),
                ('ingredients', models.JSONField(default=list, help_text='[{name, quantity, unit, catalog_id?, canonical?, optional?}] — catalog-mapped at curation')),
                ('instructions', models.JSONField(default=list, help_text='Novice step schema: [{text, time_min?, tip?}]')),
                ('base_servings', models.IntegerField(default=1, help_text='Portions the base quantities/nutrition describe', validators=[django.core.validators.MinValueValidator(1)])),
                ('base_nutrition', models.JSONField(blank=True, default=dict, help_text='Per base_servings: {calories, protein, carbs, fat}')),
                ('prep_time', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cook_time', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('source_url', models.URLField(help_text='The concrete linked source recipe (credit)', max_length=500)),
                ('source_name', models.CharField(help_text='Site/creator name shown to users', max_length=200)),
                ('source_author', models.CharField(blank=True, help_text='Original author if known', max_length=200)),
                ('license_note', models.CharField(blank=True, help_text='e.g. "paraphrased, linked with attribution"', max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('vetted', 'Vetted'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('quality_score', models.JSONField(blank=True, help_text='clarity / cultural-fit / coherence judge output', null=True)),
                ('usage_count', models.IntegerField(default=0, help_text='For variety/popularity ranking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curated Recipe',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'cuisine'], name='diet_planne_status_5d53e3_idx'), models.Index(fields=['status', 'difficulty'], name='diet_planne_status_43f144_idx')],
            },
        ),
    ]
