# Generated by Django 5.2.14 on 2026-06-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0026_curatedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='curated_recipe_slug',
            field=models.SlugField(blank=True, default='', help_text='CuratedRecipe.slug this was sourced from', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_author',
            field=models.CharField(blank=True, default='', help_text='Original author if known', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_name',
            field=models.CharField(blank=True, default='', help_text='Source site/creator for attribution', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Linked source recipe (credit/backlink)', max_length=500),
        ),
    ]
