# Generated by Django 5.2.15 on 2026-06-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0027_recipe_curated_recipe_slug_recipe_source_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryplan',
            name='grounding_debug',
            field=models.JSONField(blank=True, help_text='Recipe-grounding diagnostics: {facets, coverage} for this plan', null=True),
        ),
    ]
