# Generated by Django 5.2.14 on 2026-06-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0028_dietaryplan_grounding_debug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietaryplan',
            name='pantry_basics_on',
        ),
        migrations.RemoveField(
            model_name='dietaryplan',
            name='pantry_fridge_on',
        ),
        migrations.RemoveField(
            model_name='dietaryplan',
            name='pantry_price',
        ),
        migrations.RemoveField(
            model_name='dietaryplan',
            name='shopping_list',
        ),
        migrations.RemoveField(
            model_name='dietaryplan',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='dietaryplan',
            name='currency',
            field=models.CharField(default='PLN', help_text='Currency of the plan', max_length=3),
        ),
    ]
