# Generated by Django 5.2.14 on 2026-07-27 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0031_resync_recipe_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedrecipe',
            name='created_for_user',
            field=models.ForeignKey(blank=True, help_text='Requester of a chat_web draft; only their plan may use it pre-publish', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curatedrecipe',
            name='origin',
            field=models.CharField(choices=[('curated', 'Curated batch'), ('chat_web', 'Chat web research')], db_index=True, default='curated', help_text='curated = batch pipeline; chat_web = user-triggered web research', max_length=10),
        ),
        migrations.CreateModel(
            name='RecipeResearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_identifier', models.CharField(max_length=64)),
                ('query', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('searching', 'Searching'), ('curating', 'Curating'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='queued', max_length=10)),
                ('fail_reason', models.CharField(blank=True, help_text='machine code: no_sources / all_sources_failed / gates_failed / error', max_length=60)),
                ('reply_text', models.TextField(blank=True, help_text='Czech chat line shown when the job finishes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_jobs', to='diet_planner.curatedrecipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
