# Generated by Django 5.2.15 on 2026-08-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0032_curatedrecipe_created_for_user_curatedrecipe_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedrecipe',
            name='dish_role',
            field=models.CharField(blank=True, choices=[('main', 'Main — can carry an oběd/večeře'), ('light', 'Light — breakfast/quick-supper dish'), ('soup', 'Soup — brothy, accompanies rather than carries'), ('side', 'Side — salad/dip/accompaniment'), ('dessert', 'Dessert / sweet')], db_index=True, default='', help_text="What the dish can CARRY (meal_types says when it may appear; this says whether it can be the meal). '' = untagged legacy — passes every slot until retag_dish_roles has run.", max_length=10),
        ),
    ]
