# Generated by Django 5.2.14 on 2026-08-09 09:08

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0033_curatedrecipe_dish_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietarygoal',
            name='derived_dietary_tags',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Dietary tags extracted from the prompt, comma-separated (encrypted)', null=True),
        ),
    ]
