# Generated by Django 5.2.14 on 2026-08-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0034_dietarygoal_derived_dietary_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicalingredient',
            name='availability',
            field=models.CharField(choices=[('common', 'Common — any supermarket'), ('findable', 'Findable — large store or Rohlík only'), ('specialty', 'Specialty — asian/bio shop or online only'), ('unrated', 'Unrated')], db_index=True, default='unrated', help_text='Obtainability in an ordinary Czech supermarket', max_length=10),
        ),
        migrations.AddField(
            model_name='canonicalingredient',
            name='availability_note',
            field=models.CharField(blank=True, help_text='Why this rating, e.g. "Albert ano, Lidl ne"', max_length=200),
        ),
    ]
