# Generated by Django 5.2.14 on 2026-08-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0035_ingredient_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedrecipe',
            name='adaptation_note',
            field=models.CharField(blank=True, help_text='Disclosed change vs the credited source, e.g. "Upraveno pro dostupnost v českých obchodech"', max_length=300),
        ),
        migrations.AddField(
            model_name='curatedrecipe',
            name='original_ingredients',
            field=models.JSONField(blank=True, help_text='Pre-rewrite snapshot of `ingredients`; makes a substitution revertible', null=True),
        ),
        migrations.AddField(
            model_name='curatedrecipe',
            name='shopping_blockers',
            field=models.JSONField(blank=True, default=list, help_text='Canonical slugs rated worse than common that set shopping_difficulty'),
        ),
        migrations.AddField(
            model_name='curatedrecipe',
            name='shopping_difficulty',
            field=models.CharField(choices=[('common', 'Common — any supermarket'), ('findable', 'Findable — large store or Rohlík only'), ('specialty', 'Specialty — asian/bio shop or online only'), ('unrated', 'Unrated')], db_index=True, default='unrated', help_text="Worst non-optional ingredient's availability. Denormalised — recompute_shopping_difficulty is the writer. INVARIANT: the rollup never writes 'unrated' (it maps an unrated ingredient to 'findable'), so 'unrated' here means ONLY 'not yet computed'.", max_length=10),
        ),
    ]
