# Generated by Django 5.2.15 on 2026-08-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0036_curatedrecipe_shopping_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsubstitute',
            name='purpose',
            field=models.CharField(choices=[('preference', 'General preference'), ('dietary', 'Dietary restriction'), ('availability', 'Czech shop availability')], db_index=True, default='preference', help_text="Why this swap exists; 'availability' rows drive the CZ rewrite", max_length=12),
        ),
        migrations.AddField(
            model_name='ingredientsubstitute',
            name='substitute_unit',
            field=models.CharField(blank=True, help_text='Unit after substitution; blank keeps the original', max_length=20),
        ),
    ]
