# Generated by Django 5.2.14 on 2026-09-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0037_substitute_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedrecipe',
            name='dish_family',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Dedupe key (leco, gulas, svickova…). '' = untagged, never deduped.", max_length=60),
        ),
        migrations.AddField(
            model_name='curatedrecipe',
            name='side_options',
            field=models.JSONField(blank=True, default=list, help_text='Ordered příloha keys the dish is eaten with (see services/priloha.py: chleb, brambory, ryze, knedlik, testoviny). [] = complete dish.'),
        ),
        migrations.AlterField(
            model_name='curatedrecipe',
            name='dish_role',
            field=models.CharField(blank=True, choices=[('main', 'Main — can carry an oběd/večeře'), ('supper', 'Supper — quick večeře dish (lečo, topinky); never oběd'), ('breakfast', 'Breakfast — snídaně dish (kaše, vejce, toasty)'), ('soup', 'Soup — brothy, accompanies rather than carries'), ('side', 'Side — salad/dip/accompaniment/preserving base'), ('dessert', 'Dessert / sweet'), ('light', 'Light (legacy — retag to breakfast/supper)')], db_index=True, default='', help_text="What the dish can CARRY (meal_types says when it may appear; this says whether it can be the meal). '' = untagged legacy — passes every slot until retag_dish_roles has run.", max_length=10),
        ),
    ]
