# Generated by Django 5.2.14 on 2026-09-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0038_dish_family_side_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedrecipe',
            name='demand_peak_month',
            field=models.SmallIntegerField(blank=True, help_text='Month (1-12) the dish is searched most', null=True),
        ),
        migrations.AddField(
            model_name='curatedrecipe',
            name='demand_score',
            field=models.FloatField(blank=True, help_text='Search demand relative to guláš = 100, copied at attach time', null=True),
        ),
        migrations.AddField(
            model_name='curatedrecipe',
            name='demand_term',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Demand-map term this recipe serves ('' = no measurable demand)", max_length=120),
        ),
        migrations.AddField(
            model_name='curatedrecipe',
            name='owner_rating',
            field=models.SmallIntegerField(blank=True, help_text="Owner's 1-5 appeal rating; breaks ties between recipes of the same dish", null=True),
        ),
    ]
