# Generated by Django 5.2.14 on 2026-09-29 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0039_demand_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietarygoal',
            name='breakfasts',
            field=models.IntegerField(blank=True, help_text='Number of breakfast recipes wanted (pool model)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AddField(
            model_name='dietarygoal',
            name='dinners',
            field=models.IntegerField(blank=True, help_text='Number of dinner recipes wanted (pool model)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AddField(
            model_name='dietarygoal',
            name='lunches',
            field=models.IntegerField(blank=True, help_text='Number of lunch recipes wanted (pool model)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AddField(
            model_name='dietarygoal',
            name='small_meals',
            field=models.IntegerField(blank=True, help_text='Number of small-meal recipes wanted (pool model)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AddField(
            model_name='dietarygoal',
            name='snacks',
            field=models.IntegerField(blank=True, help_text='Number of snack recipes wanted (pool model)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AddField(
            model_name='dietaryplan',
            name='meals',
            field=models.JSONField(blank=True, default=None, help_text='Pool model: flat list of meal dicts, each with slot/index/meal_identifier. NULL on legacy day-grid plans (which use `days`).', null=True),
        ),
        migrations.AlterField(
            model_name='dietarygoal',
            name='breakfast',
            field=models.BooleanField(blank=True, help_text='LEGACY: include breakfast', null=True),
        ),
        migrations.AlterField(
            model_name='dietarygoal',
            name='dinner',
            field=models.BooleanField(blank=True, help_text='LEGACY: include dinner', null=True),
        ),
        migrations.AlterField(
            model_name='dietarygoal',
            name='lunch',
            field=models.BooleanField(blank=True, help_text='LEGACY: include lunch', null=True),
        ),
        migrations.AlterField(
            model_name='dietarygoal',
            name='num_days',
            field=models.IntegerField(blank=True, help_text='LEGACY: number of days (day-grid plans only)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='dietarygoal',
            name='small_meals_per_day',
            field=models.IntegerField(blank=True, help_text='LEGACY: small meals per day', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='dietarygoal',
            name='snacks_per_day',
            field=models.IntegerField(blank=True, help_text='LEGACY: snacks per day', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='mealinstance',
            name='day_number',
            field=models.IntegerField(blank=True, help_text='LEGACY day number; NULL for pool-model meals', null=True),
        ),
        migrations.AlterField(
            model_name='mealinstance',
            name='meal_identifier',
            field=models.CharField(db_index=True, help_text='Meal identifier: <goal>:<slot>:<index> (pool) or legacy <goal>:<day>:<type>:<index>', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_identifier',
            field=models.CharField(db_index=True, help_text='Meal identifier: <goal>:<slot>:<index> (pool) or legacy <goal>:<day>:<type>:<index>', max_length=255, unique=True),
        ),
    ]
