# Generated by Django 5.2.14 on 2026-09-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0040_meal_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicalingredient',
            name='carbs_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='canonicalingredient',
            name='density_g_per_ml',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Grams per millilitre; required only for ingredients used in volume units', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='canonicalingredient',
            name='fat_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='canonicalingredient',
            name='kcal_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='canonicalingredient',
            name='nutrition_source',
            field=models.CharField(blank=True, help_text='usda:<fdc_id> | frida:<id> | manual:<note>', max_length=64),
        ),
        migrations.AddField(
            model_name='canonicalingredient',
            name='protein_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='canonicalingredient',
            name='unit_weights',
            field=models.JSONField(blank=True, default=dict, help_text='Grams for ingredient-specific count units, e.g. {"stroužek": 5, "plátek": 20}'),
        ),
        migrations.AddField(
            model_name='curatedrecipe',
            name='nutrition_blockers',
            field=models.JSONField(blank=True, default=list, help_text='Ingredient lines whose grams or nutrients could not be computed [{name, canonical, unit, reason}]. Non-empty = cannot be promoted.'),
        ),
    ]
