# Generated by Django 5.2.14 on 2026-10-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0041_nutrition_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonicalingredient',
            name='nutrition_source',
            field=models.CharField(blank=True, help_text='usda:<fdc_id> | frida:<id> | manual:<note>', max_length=255),
        ),
    ]
