# Generated by Django 5.2.14 on 2026-09-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deals', 'Weekly deals roundup'), ('recipe', 'Recipe card'), ('showcase', 'Plan showcase')], max_length=16)),
                ('iso_week', models.CharField(help_text='e.g. 2026-W37', max_length=8)),
                ('scheduled_for', models.DateField()),
                ('channels', models.JSONField(blank=True, default=list)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('caption', models.TextField(blank=True, default='')),
                ('group_variant', models.TextField(blank=True, default='')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (awaiting ✅)'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('failed', 'Failed'), ('skipped', 'Skipped (no facts)')], default='draft', max_length=16)),
                ('slack_channel', models.CharField(blank=True, default='', max_length=32)),
                ('slack_ts', models.CharField(blank=True, default='', max_length=32)),
                ('approved_by', models.CharField(blank=True, default='', max_length=32)),
                ('facebook_post_id', models.CharField(blank=True, default='', max_length=64)),
                ('pinterest_pin_id', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-scheduled_for', 'kind'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'iso_week'), name='social_post_kind_week')],
            },
        ),
    ]
