"""
Admin interface for diet_planner models.
"""
from django.contrib import admin
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.exceptions import PermissionDenied
from .models import DietaryGoal, DietaryPlan


@admin.register(DietaryGoal)
class DietaryGoalAdmin(admin.ModelAdmin):
    """Admin interface for DietaryGoal model."""
    list_display = [
        'id',
        'user',
        'status',
        'country',
        'city',
        'currency',
        'language_code',
        'created_at',
        'completed_at',
    ]
    list_filter = [
        'status',
        'country',
        'currency',
        'language_code',
        'created_at',
    ]
    search_fields = [
        'user__username',
        'user__email',
    ]
    readonly_fields = [
        'created_at',
        'updated_at',
        'completed_at',
        'celery_task_id',
    ]
    date_hierarchy = 'created_at'
    
    def get_readonly_fields(self, request, obj=None):
        """Make encrypted fields readonly to prevent decryption errors in admin."""
        readonly = list(self.readonly_fields)
        if obj:  # Editing existing object
            readonly.extend(['prompt', 'dietary_restrictions'])
        return readonly
    
    def has_delete_permission(self, request, obj=None):
        """Allow deletion - errors are handled in model's delete method."""
        return True
    
    def delete_model(self, request, obj):
        """Override delete to handle errors gracefully."""
        try:
            obj.delete()
            messages.success(request, f"Dietary Goal {obj.id} deleted successfully.")
        except Exception as e:
            messages.error(
                request,
                f"Error deleting Dietary Goal {obj.id}: {str(e)}. "
                "The goal may have been partially deleted. Please check the database."
            )
            # Re-raise to show error in admin
            raise
    
    def delete_queryset(self, request, queryset):
        """Handle bulk deletion with error handling."""
        deleted_count = 0
        errors = []
        
        for obj in queryset:
            try:
                obj.delete()
                deleted_count += 1
            except Exception as e:
                errors.append(f"Goal {obj.id}: {str(e)}")
        
        if deleted_count > 0:
            messages.success(request, f"Successfully deleted {deleted_count} dietary goal(s).")
        
        if errors:
            messages.error(request, f"Errors deleting some goals: {'; '.join(errors)}")
    
    fieldsets = (
        ('User Information', {
            'fields': ('user',)
        }),
        ('Dietary Information', {
            'fields': ('prompt', 'dietary_restrictions')
        }),
        ('Status & Processing', {
            'fields': ('status', 'celery_task_id', 'completed_at')
        }),
        ('Location', {
            'fields': ('country', 'city', 'currency', 'language_code'),
            'description': 'Currency is auto-determined from country'
        }),
        ('Timestamps', {
            'fields': ('created_at', 'updated_at')
        }),
    )


@admin.register(DietaryPlan)
class DietaryPlanAdmin(admin.ModelAdmin):
    """Admin interface for DietaryPlan model."""
    list_display = [
        'id',
        'dietary_goal',
        'total_price',
        'currency',
        'created_at',
    ]
    list_filter = [
        'currency',
        'created_at',
    ]
    readonly_fields = [
        'created_at',
        'updated_at',
    ]
    date_hierarchy = 'created_at'
    
    fieldsets = (
        ('Goal Reference', {
            'fields': ('dietary_goal',)
        }),
        ('LLM Generated Content', {
            'fields': ('meal_ideas', 'shopping_list'),
            'description': 'Content generated by LLM (meal ideas and shopping list)'
        }),
        ('Price Information', {
            'fields': ('total_price', 'currency'),
            'description': 'Calculated by Django from database (not LLM)'
        }),
        ('Timestamps', {
            'fields': ('created_at', 'updated_at')
        }),
    )
