"""
Admin interface for diet_planner models.
"""
from django.contrib import admin
from .models import DietaryGoal, DietaryPlan


@admin.register(DietaryGoal)
class DietaryGoalAdmin(admin.ModelAdmin):
    """Admin interface for DietaryGoal model."""
    list_display = [
        'id',
        'user',
        'status',
        'country',
        'city',
        'currency',
        'language_code',
        'created_at',
        'completed_at',
    ]
    list_filter = [
        'status',
        'country',
        'currency',
        'language_code',
        'created_at',
    ]
    search_fields = [
        'user__username',
        'user__email',
    ]
    readonly_fields = [
        'created_at',
        'updated_at',
        'completed_at',
        'celery_task_id',
    ]
    date_hierarchy = 'created_at'
    
    fieldsets = (
        ('User Information', {
            'fields': ('user',)
        }),
        ('Dietary Information', {
            'fields': ('prompt', 'dietary_restrictions')
        }),
        ('Status & Processing', {
            'fields': ('status', 'celery_task_id', 'completed_at')
        }),
        ('Location', {
            'fields': ('country', 'city', 'currency', 'language_code'),
            'description': 'Currency is auto-determined from country'
        }),
        ('Timestamps', {
            'fields': ('created_at', 'updated_at')
        }),
    )


@admin.register(DietaryPlan)
class DietaryPlanAdmin(admin.ModelAdmin):
    """Admin interface for DietaryPlan model."""
    list_display = [
        'id',
        'dietary_goal',
        'total_price',
        'currency',
        'created_at',
    ]
    list_filter = [
        'currency',
        'created_at',
    ]
    readonly_fields = [
        'created_at',
        'updated_at',
    ]
    date_hierarchy = 'created_at'
    
    fieldsets = (
        ('Goal Reference', {
            'fields': ('dietary_goal',)
        }),
        ('LLM Generated Content', {
            'fields': ('meal_ideas', 'shopping_list'),
            'description': 'Content generated by LLM (meal ideas and shopping list)'
        }),
        ('Price Information', {
            'fields': ('total_price', 'currency'),
            'description': 'Calculated by Django from database (not LLM)'
        }),
        ('Timestamps', {
            'fields': ('created_at', 'updated_at')
        }),
    )
