"""Per-dish recipe images.

Dish images are generated by `manage.py generate_recipe_images` into
frontend/public/food-images/dishes/<slug>.webp, committed to the repo, and
served (via the vite build + whitenoise) at /static/food-images/dishes/….
The serializer falls back to the per-category stock image when no dish image
exists for a slug.

The available-slug set is scanned once per process — images only ever change
with a deploy, which restarts the process.
"""
from functools import lru_cache
from pathlib import Path

from django.conf import settings

DISH_IMAGE_URL_PREFIX = "/static/food-images/dishes"


@lru_cache(maxsize=1)
def _dish_image_slugs() -> frozenset:
    slugs = set()
    candidates = [
        Path(settings.BASE_DIR) / "frontend" / "public",
        getattr(settings, "REACT_BUILD_DIR", None),
    ]
    for base in candidates:
        if not base:
            continue
        dishes_dir = Path(base) / "food-images" / "dishes"
        if dishes_dir.is_dir():
            slugs.update(p.stem for p in dishes_dir.glob("*.webp"))
    return frozenset(slugs)


def has_dish_image(slug: str) -> bool:
    return bool(slug) and slug in _dish_image_slugs()


def encode_webp(image_bytes: bytes, filepath, max_dim: int = 1024, quality: int = 82) -> int:
    """Encode raw image bytes (Gemini returns PNG) as an actual WebP file,
    downscaled to `max_dim`. Returns the written size in bytes. Saving the
    raw bytes with a .webp name ships ~1.5 MB PNGs — this lands ~10x smaller."""
    from io import BytesIO

    from PIL import Image

    im = Image.open(BytesIO(image_bytes)).convert("RGB")
    if max(im.size) > max_dim:
        im.thumbnail((max_dim, max_dim), Image.LANCZOS)
    im.save(filepath, "WEBP", quality=quality, method=6)
    return Path(filepath).stat().st_size


def dish_image_url(slug: str) -> str:
    return f"{DISH_IMAGE_URL_PREFIX}/{slug}.webp"
