# Generated by Django 5.2.9 on 2026-01-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login_app", "0001_add_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="free_generations_remaining",
            field=models.IntegerField(
                default=10,
                help_text="Number of free meal plan generations remaining (lifetime limit)",
            ),
        ),
    ]
