# Generated by Django 5.2.14 on 2026-06-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_userprofile_onboarding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='free_generations_remaining',
            field=models.IntegerField(default=2, help_text='Number of free meal plan generations remaining (lifetime limit)'),
        ),
    ]
