# Generated by Django 5.2.14 on 2026-07-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_alter_userprofile_free_generations_remaining'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('tier', models.CharField(blank=True, default='', max_length=20)),
                ('auth_provider', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Account Deletion',
                'verbose_name_plural': 'Account Deletions',
            },
        ),
    ]
